# -*- coding: utf-8 -*-
"""Day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T-5jstxs-vbmYlyMpZ2sx0C29A73WNxP

# Python Basics
# Python Basics
# Python Basics
# Python Basics
# Python Basics
# Python Basics
# Python Basics
# Python Basics
"""

# Question 1


print("Hello World")

# Question 2


type('89')

# Question 3


type(2.0 ** 5)

# Question 4


print("aneesha" * 2)

# Question 5


print("a" - "b")

"""# Basic Logic & Booleans

"""

# Question 6


print(6 == 7)

# Question 7


print(int('89') + 1 == 90.0)

# Question 8


print(71 // 10 == 7)

# Question 9


print(33 % 5 != 6)

# Question 10


print(not True != False and False)

"""# Variables"""

# Question 11


my_age = 19
print(my_age + 2)

# Question 12


hufflepuff_score = 20
ravenclaw_score = 30
print(ravenclaw_score > hufflepuff_score)

# Question 13


jan_sales = 1000
feb_sales = 1300
mar_sales = 1700

print(max(jan_sales, feb_sales, mar_sales))

# Question 14


pi = 3.14159
print(round(pi, 3))

# Question 15


name = 'Aneesha'
age = 19
print(f'{name} is {age}')

"""# Conditional Statements"""

# Question 16


my_age = 19
if my_age < 18:
  print('minor')
else:
  print('adult')

# Question 17


grade = 78
if grade >= 92:
  print('A')
elif grade >= 75:
  print('B')
elif grade >= 60:
  print('C')
else:
  print('below 60')

# Question 18


if 8 == 8:
  print('yo')

if True == (not False):
  print('woah')

# Question 19


person = 'dwight'
item = 'stapler'

if person == 'dwight':
  if item == 'paper':
    print('paper rules')
  else:
    print('why not paper?')
else:
  print('person ain\'t dwight')

# Question 20

person = 'dwight'
item = 'paper'

if person == 'dwight':
  if item == 'paper':
    print('paper rules')
  else:
    print('why not paper?')
else:
  print('person ain\'t dwight')

"""# Strings"""

# Question 21


my_dog = 'peanut'
print(my_dog[0] + my_dog[-2])

my_dog[-2]

# Question 22


my_dog = 'peanut'
print(my_dog[3:5])

# Question 23


my_dog = 'peanut'
print(my_dog[::-1])

# Question 24

my_dog = 'peanut'
print(my_dog.replace('p', 'P'))

# Question 25

my_dog = 'peanut'
print(my_dog.upper().lower().capitalize())

"""# Lists"""

# Question 26


stuff = [8, '4.98', 'lies', 67.90]
print(stuff[-3])

# Question 27


stuff = [8, 'lies']
nums = [1, 3]
print(stuff + nums)

# Question 28


stuff = [8, '4.98']
stuff.append(6)
stuff.append('yo')
stuff.remove(8)
stuff.pop()
print(stuff)

# Question 29


stuff = [8, '4.98', 'lies', 67.90]
stuff.pop(0)
stuff.pop(0)
stuff.append(3)

# Question 30


stuff = [8, '4.98', 'lies', 67.90]
stuff + 2

"""# For Loops"""

# Question 31


for i in range(5):
  print(i)

# Question 32


values = []

for i in range(3):
  for j in range(2):
    values.append(i * j)


print(values)

# Question 33


colors = ['red', 'green', 'blue', 'yellow']

for color in colors:
  print(len(color))

# Question 34


people = ['devi', 'paxton', 'ben']
people2 = []
for person in people:
  people2.append(person.capitalize())

for i in range(len(people)):
  people[i] = people[i].capitalize()

print(people)
print(people2)

# Question 35


twilight = ['bella', 'edward', 'jacob']

twilight = [person.capitalize() for person in people]
print(twilight)

"""# While Loops"""

# Question 36

# Question 37

# Question 38

# Question 39

# Question 40

"""# Dictionaries"""

# Question 41

# Question 42

# Question 43

# Question 44

# Question 45

"""# Miscellaneous"""

# Question 46

# Question 47

# Question 48

# Question 49

# Question 50